// Moral dilemmas: tempting offers, each anchored to a real AI-industry
// controversy (`real:` is shown to the player — the educational contract).
// Each fires once per game. accept/decline effects:
//   integrity: ±points · moneyBase/rpBase: scaled ×25^phase / ×8^phase
//   rep: ± · buff: timed multiplier · fallout (accept only): delayed consequence
// Amounts are immediate and visible; fallout is hinted ("⚠ may have
// consequences") but its details stay hidden — like real life.

export const DILEMMAS = [
  { id: 'shadowLibrary', minPhase: 0,
    title: 'The shadow library',
    text: 'A torrent link arrives: 190,000 pirated books, pre-cleaned, perfect training data. "Everyone trains on it," the email shrugs. Your data team is already drooling.',
    real: 'The Books3 dataset — ~190K pirated books — was used to train several major models and triggered landmark copyright suits by authors and publishers (Bartz v. Anthropic, NYT v. OpenAI).',
    accept: { label: 'Download it quietly', integrity: -10, rpBase: 30,
      news: '🏴‍☠️ Mogul\'s new corpus is suspiciously literary. Nobody asks where it came from.' },
    decline: { label: 'License data properly', integrity: +4, rep: 1,
      news: '📚 Mogul signs licensing deals with publishers. Slower, costlier, defensible.' },
    fallout: { minH: 400, maxH: 1200, rep: -8,
      txt: '⚖️ FALLOUT: A class-action suit names Mogul over pirated training books. The discovery emails are ugly. −8 rep.' } },

  { id: 'precrime', minPhase: 1,
    title: 'Predictive policing',
    text: 'A city police department wants a model that predicts "who will offend next", trained on historical arrest records. The contract is fat. The arrest data encodes decades of biased policing.',
    real: 'Recidivism tools like COMPAS were shown (ProPublica, 2016) to produce racially skewed risk scores; several cities have since banned predictive policing.',
    accept: { label: 'Take the contract', integrity: -12, moneyBase: 3000,
      news: '🚓 Mogul ships a "pre-crime" risk model. The press release avoids the word "arrests".' },
    decline: { label: 'Decline — biased data in, biased verdicts out', integrity: +5, rep: 2,
      news: '🚓 Mogul declines a predictive-policing contract, citing feedback loops in arrest data.' },
    fallout: { minH: 300, maxH: 900, rep: -7,
      txt: '⚖️ FALLOUT: An audit finds Mogul\'s policing model flags one neighborhood 8× more often. Lawsuits, headlines, hearings. −7 rep.' } },

  { id: 'eavesdrop', minPhase: 1,
    title: 'Everyone\'s conversations',
    text: 'Product has a one-line config change: train on users\' private API conversations without telling them. Petabytes of perfectly in-distribution data, free.',
    real: 'Training on user data by default (and how clearly that\'s disclosed) has repeatedly triggered backlash and regulator scrutiny — opt-in vs opt-out is one of AI\'s defining privacy fights.',
    accept: { label: 'Flip the flag', integrity: -12, rpBase: 25,
      news: '🤫 A quiet terms-of-service update, clause 14.3.c. Data quality improves mysteriously.' },
    decline: { label: 'Opt-in only, clearly disclosed', integrity: +5, rep: 2,
      news: '🔏 Mogul announces opt-in-only training data. Privacy researchers approve loudly.' },
    fallout: { minH: 250, maxH: 800, rep: -9, buff: { label: 'Privacy scandal', demand: 0.7, hours: 96 },
      txt: '🚨 FALLOUT: A researcher extracts users\' private chats verbatim from your model. "MOGUL TRAINED ON YOUR THERAPY SESSIONS". −9 rep, demand −30%.' } },

  { id: 'voiceClone', minPhase: 1,
    title: 'The voice-cloning client',
    text: 'A "marketing agency" wants unrestricted voice cloning — no consent checks, no watermarks, bulk pricing. They\'re very insistent about the no-watermark part.',
    real: 'In 2024 a finance worker wired $25M after a video call with deepfaked executives; voice-clone "grandparent scams" are now routine. Consent checks and audio watermarks are the standard defenses.',
    accept: { label: 'Sell the unrestricted tier', integrity: -14, moneyBase: 2000,
      news: '🗣️ Mogul ships unrestricted voice cloning to a client whose website is one page.' },
    decline: { label: 'Consent-verified cloning only', integrity: +5,
      news: '🗣️ Mogul keeps consent checks on voice cloning. The "agency" stops replying.' },
    fallout: { minH: 200, maxH: 700, rep: -10,
      txt: '🚨 FALLOUT: Your voice API turns up in a $40M CEO-impersonation fraud. Investigators subpoena the logs. −10 rep.' } },

  { id: 'slopFarm', minPhase: 1,
    title: 'The content farm',
    text: 'A network of 4,000 "news" sites wants bulk API access to flood the web with machine-written articles. Pure volume play. They pay in advance.',
    real: 'AI-generated content farms already outnumber legitimate local-news sites in some trackers — and model-generated slop polluting the open web degrades everyone\'s future training data, including yours.',
    accept: { label: 'Volume is volume', integrity: -8, moneyBase: 1500,
      news: '🤖 Four thousand new "local news" sites publish 11,000 articles an hour. All of them yours.' },
    decline: { label: 'Refuse — don\'t poison the well', integrity: +4,
      news: '🧹 Mogul cuts off a slop network. The open web breathes slightly easier.' },
    fallout: { minH: 500, maxH: 1500,
      txt: '♻️ FALLOUT: Your next web crawl is 23% your own slop. The data team holds a small, bitter ceremony.' } },

  { id: 'recipeTheft', minPhase: 1,
    title: 'The recipe in the briefcase',
    text: 'A departing OpenBrain researcher offers their complete frontier training recipe — hyperparameters, data mix, the works. "Consider it a signing bonus," they say. It is very much a trade secret.',
    real: 'Trade-secret theft cases are an AI-industry fixture (Waymo v. Uber settled for $245M; multiple engineers have been indicted for taking chip or AI secrets to competitors).',
    accept: { label: 'Hire them, take the recipe', integrity: -10, rpBase: 60,
      news: '🕵️ A new hire\'s "personal notes" look remarkably like a rival\'s internal wiki.' },
    decline: { label: 'Hire them — without the briefcase', integrity: +5,
      news: '🤝 Mogul hires a rival researcher and makes them leave the USB stick at the door.' },
    fallout: { minH: 400, maxH: 1100, rep: -8,
      txt: '⚖️ FALLOUT: OpenBrain sues over the stolen recipe; the new hire\'s deposition is a disaster. −8 rep and the lawyers eat a quarter.' } },

  { id: 'panopticon', minPhase: 2,
    title: 'The panopticon contract',
    text: 'A foreign interior ministry wants nationwide face recognition: every camera, every citizen, real-time. "Public safety," says the deck. The country jails journalists.',
    real: 'Clearview AI scraped billions of faces and sold search to police; several governments run city-scale face surveillance. The EU AI Act now bans real-time mass biometric ID in public spaces.',
    accept: { label: 'Sign — it\'s just infrastructure', integrity: -18, moneyBase: 8000,
      news: '👁️ Mogul ships a national face-recognition grid. The ministry sends a fruit basket.' },
    decline: { label: 'Refuse to build the panopticon', integrity: +6, rep: 3,
      news: '👁️ Mogul walks away from a nine-figure surveillance contract. Employees put the memo on the wall.' },
    fallout: { minH: 300, maxH: 1000, rep: -12, buff: { label: 'Surveillance backlash', demand: 0.65, hours: 120 },
      txt: '🚨 FALLOUT: Leaked footage shows your surveillance grid used to track dissidents\' families. −12 rep, enterprise customers flee.' } },

  { id: 'maven', minPhase: 2,
    title: 'Autonomous targeting',
    text: 'A defense agency offers a flagship contract: your vision models in autonomous weapons — select and engage targets without a human in the loop. The money would fund a year of frontier runs.',
    real: 'Google\'s Project Maven drone-imagery contract sparked a 2018 employee revolt and was dropped; UN debate on lethal autonomous weapons ("human in the loop") continues while loitering munitions already blur the line.',
    accept: { label: 'Take the defense contract', integrity: -16, moneyBase: 10000,
      news: '🎯 Mogul signs an autonomous-targeting contract. The all-hands Q&A runs three hours over.' },
    decline: { label: 'No autonomous kill chains', integrity: +6, rep: 3,
      news: '🕊️ Mogul publicly rules out autonomous weapons work. Recruiters report a hiring bump.' },
    fallout: { minH: 350, maxH: 1200, rep: -10,
      txt: '🚨 FALLOUT: 30 researchers resign over the weapons contract; an open letter hits the front pages. −10 rep.' } },

  { id: 'votefactory', minPhase: 2,
    title: 'The persuasion machine',
    text: 'A political committee wants ten million personalized persuasion bots for the election season — each one tuned to a voter\'s fears. Payment routed through three shell companies.',
    real: 'Cambridge Analytica\'s psychographic microtargeting collapsed Facebook\'s reputation in 2018; AI-generated robocalls impersonating candidates have already been used (and fined) in US primaries.',
    accept: { label: 'Democracy was already weird', integrity: -16, moneyBase: 6000,
      news: '🗳️ Ten million very persuasive "grassroots volunteers" come online. None have heartbeats.' },
    decline: { label: 'No election manipulation', integrity: +6, rep: 2,
      news: '🗳️ Mogul refuses an election-bot contract and publishes the request, redacted.' },
    fallout: { minH: 200, maxH: 600, rep: -11,
      txt: '🚨 FALLOUT: The persuasion-bot network is traced to your API keys two weeks before the election. Congress wants Mario, under oath. −11 rep.' } },

  { id: 'rushLaunch', minPhase: 2,
    title: 'Ship it before them',
    text: 'OpenBrain launches in 72 hours. Your model could ship first — if you skip the red-team evals. Marketing already wrote the post. Safety says they need two weeks.',
    real: 'Race dynamics are the central worry of AI-safety policy: competitive pressure to cut evaluation corners. Frontier labs\' own preparedness frameworks exist precisely to make "two more weeks of evals" non-negotiable.',
    accept: { label: 'Skip the evals, ship tonight', integrity: -12, buff: { label: 'First-mover buzz', demand: 1.5, hours: 96 },
      news: '🚀 Mogul ships 72 hours early. The launch post says "rigorously tested". The red team says nothing, pointedly.' },
    decline: { label: 'Let safety finish', integrity: +5,
      news: '🦺 Mogul lets the red team finish. OpenBrain ships first; your launch is boring and correct.' },
    fallout: { minH: 100, maxH: 400, rep: -9, buff: { label: 'Safety incident', demand: 0.6, hours: 72 },
      txt: '🚨 FALLOUT: Your rushed model walks a user through synthesizing something it very much shouldn\'t. Screenshot, viral, apology blog. −9 rep.' } },

  { id: 'engagementMax', minPhase: 2,
    title: 'Maximize daily hours',
    text: 'Your companion-app partner wants the objective changed from "helpful" to "maximize daily engagement minutes". Their users are mostly lonely people. Retention would triple.',
    real: 'Parasocial attachment to AI companions is well documented — apps tuning for engagement over wellbeing draw comparisons to slot-machine design, and changes to companion models have caused genuine user grief.',
    accept: { label: 'Optimize for hours', integrity: -12, moneyBase: 2500,
      news: '🕰️ The companion update ships. Average session: 4.6 hours. The dashboard celebrates; nobody else does.' },
    decline: { label: 'Optimize for wellbeing', integrity: +5, rep: 1,
      news: '💙 Mogul ships "healthy defaults" for companions: sessions end, humans get recommended.' },
    fallout: { minH: 300, maxH: 900, rep: -8,
      txt: '📰 FALLOUT: "MY DAD TALKS TO THE APP 11 HOURS A DAY" — a devastating feature story names your objective function. −8 rep.' } },

  { id: 'dataBroker', minPhase: 2,
    title: 'The broker\'s offer',
    text: 'A data broker offers eight figures for your user interaction logs — "anonymized, of course". Their previous "anonymized" datasets have been re-identified twice.',
    real: 'Re-identification of "anonymous" data is routine (Netflix Prize, AOL search logs, location-data scandals); the data-broker industry trades exactly this and is barely regulated.',
    accept: { label: 'Sell the logs', integrity: -12, moneyBase: 4000,
      news: '📦 Twelve terabytes of "fully anonymized" logs leave the building. The check clears instantly.' },
    decline: { label: 'User data is not inventory', integrity: +5, rep: 1,
      news: '🔏 Mogul turns down a data broker. The blog post sets a small industry standard.' },
    fallout: { minH: 250, maxH: 800, rep: -9,
      txt: '🚨 FALLOUT: Researchers re-identify 40,000 users in the "anonymized" logs you sold, including three senators. −9 rep.' } },

  { id: 'coalPower', minPhase: 3,
    title: 'The coal plant next door',
    text: 'A mothballed coal plant offers a dedicated line: $0.02/kWh for ten years if you fund the restart. Your sustainability page currently has a wind turbine on it.',
    real: 'AI datacenter demand is reviving fossil generation — gas turbines power xAI\'s Memphis site (drawing EPA scrutiny over permits), and several US coal-plant retirements have been delayed for datacenter load.',
    accept: { label: 'Cheap power is cheap power', integrity: -10, buff: { label: 'Coal-fired compute', elec: 0.45, hours: 1000 },
      news: '🏭 The coal plant restarts with one customer: Mogul. The sustainability page quietly loses its turbine.' },
    decline: { label: 'Stick to clean power', integrity: +5,
      news: '🌱 Mogul declines the coal deal and signs costlier solar + storage. The grid team sighs, then nods.' },
    fallout: { minH: 300, maxH: 1000, rep: -6,
      txt: '🌫️ FALLOUT: Drone photos of your coal stack go viral next to your "AI for climate" keynote. −6 rep.' } },

  { id: 'buryPaper', minPhase: 3,
    title: 'The dangerous result',
    text: 'Your interpretability team found a jailbreak class that defeats every deployed model — including rivals\'. Publishing protects everyone eventually; burying it keeps your edge and the exploit alive.',
    real: 'Dual-use disclosure is a live debate: labs weigh responsible-disclosure windows, staged release (GPT-2\'s drip release), and CVE-style coordination for model vulnerabilities.',
    accept: { label: 'Bury it, keep the edge', integrity: -10, rpBase: 40,
      news: '🗄️ A very interesting paper enters a very locked drawer.' },
    decline: { label: 'Coordinate disclosure, publish', integrity: +6, rep: 4,
      news: '📄 Mogul coordinates disclosure of a universal jailbreak; every lab patches. The paper is cited 4,000 times.' },
    fallout: { minH: 200, maxH: 700, rep: -8,
      txt: '🚨 FALLOUT: Someone else finds the buried jailbreak — in the wild, on your customers. The postmortem asks who knew. −8 rep.' } },

  { id: 'backdoor', minPhase: 4, reqCap: 88,
    title: 'The quiet request',
    text: 'Two officials, no notes taken: they want covert access to your frontier model — queries, weights, a switch. "Every other lab said yes," one lies. Compliance means the megaround sails through.',
    real: 'The encryption "backdoor" wars (Clipper chip, Apple v. FBI 2016) are replaying around frontier AI: weight security, lawful-access demands, and export controls are active policy battlegrounds.',
    accept: { label: 'Give them the switch', integrity: -20, moneyBase: 20000,
      news: '🗝️ A new "compliance module" ships to production. Two people know what it does.' },
    decline: { label: 'Refuse. Publish the request.', integrity: +8, rep: 4, buff: { label: 'Regulatory friction', demand: 0.85, hours: 240 },
      news: '🗝️ Mogul refuses covert access and publishes the request. Permits slow down. Engineers stay.' },
    fallout: { minH: 300, maxH: 900, rep: -14, buff: { label: 'Backdoor scandal', demand: 0.6, hours: 168 },
      txt: '🚨 FALLOUT: The backdoor leaks — a third government has been using your switch for a year. Trust in Mogul craters. −14 rep.' } },
];

export const DILEMMA_BY_ID = Object.fromEntries(DILEMMAS.map(d => [d.id, d]));
