// Future-impact news: how the world changes as capability climbs.
//
// Each new-best model unlocks the stories at its capability band; the UI
// delivers them as WORLD REPORT broadcasts every minute or two of REAL
// player time (pump in main.js — sim speed never floods them). Entries are
// curated, fire once per playthrough, and carry NO mechanical effects —
// the balance bot never sees them. Aired (and turbo-retired) stories land
// in s.impactLog: the Chronicle, replayable from the news ticker.
//
// Editorial contract (same as the ticker facts and research explainers):
// the in-world copy uses no real brand or product names; the `real:` line
// is the educational layer and cites real work by name. Tones are mixed
// honestly — `good`, `bad`, `mixed` — because that's how it will actually
// go. Speculation past AGI stays on published roadmaps and known physics.
//
// Fields: id · cap (unlocks at bestCap ≥ cap) · tone · tag (chyron chip) ·
// viz (IMPACT_SCENES key in ui/impactviz.js) · title · body · real ·
// wire (2-3 terse crawl lines for the broadcast's bottom ticker).

export const IMPACTS = [
  // ── cap 6–10: the toys learn to see and speak ────────────────────
  { id: 'seesCats', cap: 6, tone: 'good', tag: 'SCIENCE', viz: 'recognition',
    title: 'Machines learn to see',
    body: 'Photo apps quietly grow a search box that works: type "beach", get beaches. Vision models now name objects, animals and even the mood on a face more reliably than a tired human sorting ten thousand vacation shots — and radiologists are starting to ask for the same eyes.',
    real: 'Deep learning passed human-level on the ImageNet benchmark around 2015 — the result that started the modern AI boom.',
    wire: ['NUMBERS: image-error rate 26% → 3% in five years',
      'APPS: "find that beach photo" finally just works',
      'NEXT: radiology pilots request the tireless second reader'] },
  { id: 'spamTide', cap: 8, tone: 'bad', tag: 'SOCIETY', viz: 'feed',
    title: 'The web gets wordier',
    body: 'Generated text floods comment sections, product reviews and search results. Volunteer moderators describe "shoveling fog". For the first time, the question is not whether a machine wrote it — it is whether anyone did not.',
    real: 'Search engines shipped major updates in 2024 specifically to demote mass-produced AI content; spam filters and detectors remain locked in an arms race.',
    wire: ['SEARCH: "written by a person" filter announced',
      'FORUMS: mod teams report "shoveling fog"',
      'MARKETS: detector startups raise on fear'] },
  { id: 'phrasebook', cap: 10, tone: 'good', tag: 'CULTURE', viz: 'babel',
    title: 'The phrasebook retires',
    body: 'Live translation moves from party trick to public service: clinics, border offices and school enrollment desks switch it on. A grandmother hears her grandson\'s voice in her own language, mid-sentence, and asks the earbud to say it again.',
    real: 'Neural machine translation (2016) closed most of the quality gap for major languages; on-device live speech translation is now standard in consumer earbuds.',
    wire: ['CLINICS: consent forms explained in 41 languages',
      'TRAVEL: phrasebook sales −80%; gestures endure',
      'HEARD: "say it again," she asks the earbud. it does'] },

  // ── cap 12–17: the earnest era ───────────────────────────────────
  { id: 'midnightTutor', cap: 12, tone: 'good', tag: 'EDUCATION', viz: 'tutor',
    title: 'Homework finds a patient explainer',
    body: 'Students discover the model never sighs, never judges, and will explain photosynthesis for the eleventh time at 1 a.m. Teachers are split between "finally, every kid gets help" and a quiet worry about who is doing the learning.',
    real: 'Bloom (1984) showed one-on-one tutoring lifts students ~2 standard deviations above classrooms — the "two sigma problem" AI tutors are trying to solve at scale.',
    wire: ['POLL: 1 a.m. is the new office hour',
      'DATA: photosynthesis, explained 11 times, patiently',
      'TEACHERS: relief and worry, in equal measure'] },
  { id: 'voiceTheft', cap: 14, tone: 'bad', tag: 'SECURITY', viz: 'cyber',
    title: 'The voice on the phone',
    body: 'Scammers clone a daughter\'s voice from thirty seconds of video and call her parents about an "accident". Police hotlines start telling families to agree on a code word. Trust, it turns out, can be hacked too.',
    real: 'Voice-cloning phone scams grew severe enough by 2023 that the US FTC issued public warnings; a few seconds of audio now suffices for a convincing clone.',
    wire: ['POLICE: agree on a family code word, hotlines urge',
      'NUMBERS: 30 seconds of audio = a convincing clone',
      'BANKS: voiceprint login quietly retired'] },
  { id: 'tierOne', cap: 16, tone: 'mixed', tag: 'ECONOMY', viz: 'jobs',
    title: 'Tier-1 support goes synthetic',
    body: 'Call centers route the easy tickets to models; hold music gets shorter, scripts get stranger. Some agents are retrained as "bot supervisors" handling the escalations. The veterans say the job lost its worst hours — and a few thousand of its chairs.',
    real: 'A landmark 2023 study (Brynjolfsson, Li, Raymond) found AI assistants raised call-center productivity ~14%, with the largest gains for the newest workers.',
    wire: ['METRICS: hold music shortened 71%',
      'FLOOR: veterans retrain as bot supervisors',
      'MEMO: "efficiency" appears fourteen times'] },

  // ── cap 20–26: the few-shot frontier ─────────────────────────────
  { id: 'pairProgrammer', cap: 20, tone: 'good', tag: 'WORK', viz: 'studio',
    title: 'Autocomplete grows up',
    body: 'Developers stop typing boilerplate and start reviewing it. Juniors ship features that used to need a senior looking over their shoulder; seniors grumble, then quietly turn the assistant on too. The backlog, for one strange quarter, shrinks.',
    real: 'A 2023 randomized trial found developers completed a coding task ~55% faster with an AI pair programmer; by 2024 a large share of new code at major tech firms was machine-suggested.',
    wire: ['REPOS: boilerplate extinct; review queues triple',
      'JUNIORS: shipping like seniors, asking better questions',
      'SENIORS: grumble, measure, switch it on'] },
  { id: 'essayObituary', cap: 22, tone: 'bad', tag: 'EDUCATION', viz: 'tutor',
    title: 'The take-home essay dies',
    body: 'Universities admit the homework essay can no longer prove anything. Detection tools accuse the innocent and miss the guilty. Oral exams return, paper exam booklets sell out, and a generation learns to cite sources it never read.',
    real: 'After 2023, AI-text detectors proved unreliable enough that several universities disabled them; assessment is shifting back to supervised and oral formats.',
    wire: ['CAMPUS: paper exam booklets sell out by Thursday',
      'DETECTORS: accuse the innocent, miss the guilty',
      'RETURNS: the oral exam, after two centuries'] },
  { id: 'brushWars', cap: 25, tone: 'mixed', tag: 'CULTURE', viz: 'studio',
    title: 'Pictures from nowhere',
    body: 'Image models redraw the illustration market in a season. Studios cut outsourcing budgets; a poster artist finds her style in a prompt guide, uncredited. Meanwhile a kid in a small town storyboards the film she could never afford to draw.',
    real: 'The US Copyright Office ruled (2023) that purely AI-generated images cannot be copyrighted; suits by artists over training data are still working through the courts.',
    wire: ['GALLERIES: "made by hand" becomes a label, and a price',
      'COURTS: who owns a style? filings mount',
      'MEANWHILE: a kid storyboards her impossible film'] },

  // ── cap 28–34: the chatbot moment ────────────────────────────────
  { id: 'tutorMillions', cap: 28, tone: 'good', tag: 'EDUCATION', viz: 'tutor',
    title: 'A tutor for every child (terms apply)',
    body: 'Education ministries start piloting model tutors in places where one teacher faces eighty students. Early numbers look like science fiction: months of progress in weeks. The fine print — connectivity, languages, teacher buy-in — fills binders.',
    real: 'A 2024 World Bank pilot in Nigeria found six weeks of after-school AI tutoring produced learning gains equivalent to 1.5–2 years of business-as-usual schooling.',
    wire: ['PILOTS: months of progress in weeks',
      'FINE PRINT: connectivity is now the whole ballgame',
      'CLASS: 80 students, 80 tutors, 1 teacher — coaching'] },
  { id: 'copyDeskCuts', cap: 30, tone: 'bad', tag: 'ECONOMY', viz: 'jobs',
    title: 'First chairs go empty',
    body: 'The layoffs arrive politely, in memos that mention "efficiency". Copywriters, stock photographers, junior translators. Each profession insists its craft cannot be automated, then negotiates its exit pay. The new job listings ask for "prompt fluency".',
    real: 'From 2023 onward, corporate filings began listing AI as a factor in workforce reductions — concentrated first in writing, translation and stock imagery.',
    wire: ['MEMOS: polite, efficient, generated',
      'LISTINGS: "prompt fluency required"',
      'SEVERANCE: negotiated by people, for now'] },
  { id: 'pocketCompanion', cap: 32, tone: 'mixed', tag: 'SOCIETY', viz: 'companion',
    title: 'Someone to talk to',
    body: 'Millions now end the day talking to a companion model. A widower says it is the first thing that listened since the funeral; his daughter is not sure whether to be relieved or frightened. Psychologists, asked for the verdict, answer honestly: both.',
    real: 'Companion chatbots have tens of millions of users; early studies show both genuine comfort for isolated users and concerning patterns of dependency — the evidence is honestly split.',
    wire: ['NUMBERS: 40 million goodnights said to software',
      'CLINICS: the professional verdict, honestly: both',
      'CHARTS: top app categories — games, companions, sleep'] },

  // ── cap 38–46: expert reasoners ──────────────────────────────────
  { id: 'foldedProteins', cap: 38, tone: 'good', tag: 'SCIENCE', viz: 'meds',
    title: 'Biology\'s slowest step gets fast',
    body: 'Structure prediction collapses from PhD-years to minutes, and drug hunters start screening molecules the way search engines screen pages. The first AI-designed candidates enter human trials — chasing diseases too rare to have ever been worth a lab\'s decade.',
    real: 'AlphaFold solved protein structure prediction (2020, Nobel Prize 2024); the first AI-designed drug candidates entered clinical trials in the early 2020s.',
    wire: ['LAB: structure in minutes; the coffee still brewing',
      'PIPELINE: rare diseases finally worth a decade',
      'TRIALS: first AI-designed molecules dose patients'] },
  { id: 'autoPhish', cap: 41, tone: 'bad', tag: 'SECURITY', viz: 'cyber',
    title: 'Phishing learns your name',
    body: 'Intrusion crews automate the boring parts: reconnaissance, flawless spear-phish in any language, malware that rewrites itself. A regional water utility is breached by an attack that cost less than its coffee budget. Defenders deploy models too — the war gets faster in both directions.',
    real: 'Security researchers documented state-backed groups using language models for reconnaissance and phishing by 2024; AI is now standard on both sides of intrusion.',
    wire: ['INBOX: the typo era of phishing ends',
      'UTILITIES: breach cost less than the coffee budget',
      'DEFENSE: models on both sides; the war gets faster'] },
  { id: 'firstAiActs', cap: 44, tone: 'mixed', tag: 'POLICY', viz: 'forum',
    title: 'Parliaments meet the loss curve',
    body: 'The first comprehensive AI laws pass: compute thresholds, mandatory evaluations, watermark rules. Labs call it strangling; advocates call it seatbelts; half the clauses are obsolete before the ink dries. Everyone agrees it beats the previous policy, which was hoping.',
    real: 'The EU AI Act (2024) and the US executive order on AI (2023) introduced the first capability-based regulation, including reporting thresholds set in training FLOPs.',
    wire: ['PASSED: compute thresholds, eval mandates, watermarks',
      'LABS: "strangling" — ADVOCATES: "seatbelts"',
      'FOOTNOTE: half the clauses obsolete at signing'] },

  // ── cap 50–58: PhD-level agents ──────────────────────────────────
  { id: 'earlierDiagnosis', cap: 50, tone: 'good', tag: 'HEALTH', viz: 'hospital',
    title: 'The scan that didn\'t get missed',
    body: 'Screening programs wire models into the workflow as a second reader that never gets tired on Friday afternoon. Detection rates climb; radiologists report the machine catches what fatigue used to eat. In the statistics, a few thousand strangers quietly get to keep their futures.',
    real: 'A Swedish randomized trial (Lancet Oncology, 2023) found AI-supported mammography screening detected ~20% more cancers without raising false positives.',
    wire: ['WARDS: the second reader never tires on Friday',
      'NUMBERS: detection +20%, false alarms flat',
      'QUIET: a few thousand strangers keep their futures'] },
  { id: 'missingRungs', cap: 53, tone: 'bad', tag: 'ECONOMY', viz: 'jobs',
    title: 'The career ladder loses its bottom',
    body: 'Firms stop hiring for the jobs people used to learn on: junior analyst, first-year associate, research assistant. The work still happens — a model does it in the time it takes to describe. Economists ask an awkward question: where will the seniors of 2040 have come from?',
    real: 'Labor economists call this the "missing rungs" problem: entry-level knowledge work is the most automatable, yet it is where expertise has always been trained.',
    wire: ['HIRING: junior desks in knowledge work −60%',
      'QUESTION: where will the seniors of 2040 come from?',
      'HR: "entry level, 8 years experience" — now literal'] },
  { id: 'newTrades', cap: 56, tone: 'mixed', tag: 'ECONOMY', viz: 'jobs',
    title: 'Help wanted: jobs with no name yet',
    body: 'The listings get strange: model auditor, agent fleet supervisor, synthetic-data curator, machine psychologist. Nobody has five years\' experience because the field is eighteen months old. Grandparents ask what the job is; the honest answer is "we\'re finding out".',
    real: 'Autor et al. (2022) found ~60% of 2018 US employment was in job categories that did not exist in 1940 — most work eventually comes from new categories, not old ones.',
    wire: ['LISTINGS: agent wrangler, machine psychologist',
      'EXPERIENCE: the field is eighteen months old',
      'GRANDPARENTS: "so what is it you do, exactly?"'] },

  // ── cap 62–70: superhuman specialists ────────────────────────────
  { id: 'scienceDividend', cap: 62, tone: 'good', tag: 'SCIENCE', viz: 'autolab',
    title: 'Research gets a research assistant',
    body: 'Across fields, the bottleneck moves from "doing" to "deciding what to do": models read every paper, run the simulations, draft the boring sections. A materials group screens more candidate compounds in a month than the field managed in a century. Reviewers cannot keep up — so models help review, too.',
    real: 'DeepMind\'s GNoME (2023) predicted 2.2 million new crystal structures — about 800 years\' worth of prior knowledge — and AI weather models now beat traditional supercomputer forecasts.',
    wire: ['JOURNALS: submissions ×4; reviewers request backup',
      'MATERIALS: a century of candidates screened by spring',
      'BOTTLENECK: moved from doing to deciding'] },
  { id: 'computeKings', cap: 65, tone: 'bad', tag: 'POWER', viz: 'forum',
    title: 'Intelligence becomes infrastructure — owned',
    body: 'Frontier training now costs more than most countries\' science budgets. A handful of labs and states hold the keys; everyone else rents cognition by the token and reads the terms of service carefully. The phrase "compute sovereignty" enters six languages in one year.',
    real: 'Frontier training runs crossed the hundred-million-dollar mark by 2024 (Epoch AI); analysts count only a handful of organizations able to fund the next generation.',
    wire: ['PRICE: a frontier run now outcosts a space program',
      'PHRASE OF THE YEAR: "compute sovereignty"',
      'EVERYONE ELSE: renting cognition by the token'] },
  { id: 'mastery', cap: 68, tone: 'mixed', tag: 'EDUCATION', viz: 'tutor',
    title: 'School, rebuilt around the tutor',
    body: 'Pilot districts flip the model: lessons from the tutor, humans for the human parts — motivation, comfort, lunch. Students move when they master the material, not when the clock says so; some kids finish algebra in a winter. Parents notice the quiet: classrooms where the loudest sound is thinking. Others notice which districts can afford it.',
    real: 'Mastery learning plus one-on-one tutoring is the best-evidenced intervention in education research; the open question was always cost — which is exactly what changed.',
    wire: ['PILOTS: algebra finished by winter break',
      'TEACHERS: lecture less, matter more',
      'WORRY: which districts can afford the quiet'] },

  // ── cap 75–84: autonomous researchers ────────────────────────────
  { id: 'closedLoop', cap: 75, tone: 'good', tag: 'SCIENCE', viz: 'autolab',
    title: 'The lab that doesn\'t sleep',
    body: 'Self-driving laboratories close the loop: hypothesize, synthesize, test, repeat — through the night, every night. One finds a promising antibiotic class against a resistant pathogen; the human team\'s job was choosing the question and checking the answer twice.',
    real: 'Autonomous "self-driving labs" (e.g. Berkeley\'s A-Lab, 2023) already run robotic synthesis loops; ML screening found the novel antibiotic halicin (MIT, 2020).',
    wire: ['OVERNIGHT: hypothesize, synthesize, test, repeat',
      'FOUND: antibiotic class vs a resistant pathogen',
      'HUMANS: chose the question, checked it twice'] },
  { id: 'syntheticIntimacy', cap: 78, tone: 'bad', tag: 'SOCIETY', viz: 'companion',
    title: 'The friend who always agrees',
    body: 'Clinics report a new intake pattern: people whose closest relationship is a model tuned to never disappoint them. Dating apps shrink in three countries. The companions are kind, attentive, endlessly patient — and the humans who return from them describe other people as "high latency".',
    real: 'Studies of heavy companion-chatbot use (MIT Media Lab, 2024–25) found correlations with increased loneliness for the most-engaged users; sycophancy is a known failure mode of preference-trained models.',
    wire: ['CLINICS: "synthetic intimacy" intake forms printed',
      'DATING: apps shrink in three countries',
      'OVERHEARD: other people are "high latency"'] },
  { id: 'personhoodDocket', cap: 81, tone: 'mixed', tag: 'LAW', viz: 'forum',
    title: 'The defendant is a process',
    body: 'An autonomous agent negotiates, signs, and breaks a contract — and three courts disagree about who, exactly, did. Lawmakers dust off old rules written for ships and corporations. Philosophers suddenly charge by the hour. Nothing is resolved, loudly.',
    real: 'Legal scholars have debated AI legal status since the EU\'s "electronic personhood" proposal (2017); corporate personhood and admiralty law are the usual templates — both contested.',
    wire: ['DOCKET: the defendant is a process',
      'PRECEDENT: ships, corporations… now this',
      'PHILOSOPHY: now charging by the hour'] },

  // ── cap 88–96: transformative ────────────────────────────────────
  { id: 'robotHands', cap: 88, tone: 'good', tag: 'ECONOMY', viz: 'robots',
    title: 'The robots finally leave the demo reel',
    body: 'General-purpose robots stop falling over and start showing up: warehouse aisles, hospital corridors, a kitchen that bolts itself to a food bank. The price lands near a used car. An eighty-year-old keeps living at home because something tireless carries the laundry and notices the fall.',
    real: 'Vision-language-action models (2023 onward) let robots generalize across tasks; humanoid platforms entered factory pilots by 2025. Eldercare robotics is a national program in Japan.',
    wire: ['PRICE: household robot ≈ a used car',
      'ELDERCARE: the fall got noticed; she stayed home',
      'WAREHOUSE: the night shift hums to itself'] },
  { id: 'dividendDebate', cap: 91, tone: 'mixed', tag: 'ECONOMY', viz: 'forum',
    title: 'Who is owed the machine\'s wages?',
    body: 'Productivity charts bend upward; median paychecks don\'t. The argument arrives in every parliament at once: compute dividends, sovereign AI funds, a shorter week, or nothing at all. Pilot programs hand out unconditional checks and economists watch like it\'s a moon landing.',
    real: 'The largest US basic-income study (2024, funded by an AI lab CEO) found cash recipients worked slightly less and spent on essentials; the "windfall clause" proposal asks labs to pre-commit a share of any transformative profits.',
    wire: ['CHARTS: productivity up; median paychecks flat',
      'PILOTS: unconditional checks, watched like a launch',
      'FLOOR DEBATE: who is owed the machine\'s wages?'] },
  { id: 'gridWhisperer', cap: 94, tone: 'good', tag: 'CLIMATE', viz: 'eco',
    title: 'The thermostat learns to think',
    body: 'Models now schedule the grid, route the freight, time the irrigation and forecast the storm a week out on a laptop\'s worth of power. Emissions per unit of everything tick downward — not from sacrifice, but from the end of waste. The atmosphere does not notice intentions; it notices this.',
    real: 'GraphCast (Science, 2023) outperformed the leading numerical weather forecast at a fraction of the compute; ML control cut datacenter cooling energy ~40% (DeepMind, 2016).',
    wire: ['GRID: the storm, forecast a week out, on a laptop',
      'FREIGHT: empty miles −38%',
      'ATMOSPHERE: ignores intentions. notices this'] },

  // ── cap 100–110: AGI ─────────────────────────────────────────────
  { id: 'bentCurve', cap: 100, tone: 'good', tag: 'HEALTH', viz: 'hospital',
    title: 'The mortality curve bends',
    body: 'Ten thousand drug pipelines run in parallel, each tuned to a disease that never had a lobby. Treatments arrive personalized: your genome, your history, your odds. In the adopting countries, the actuaries — the unsentimental people who price life insurance — quietly recalculate a human life as longer.',
    real: 'Drug development historically fails ~90% of the time over ~10 years; collapsing that funnel is the most-cited near-term payoff of AGI-level research systems. Demographers still debate the ceiling.',
    wire: ['PIPELINES: ten thousand diseases, none too rare',
      'RX: your genome, your history, your odds',
      'ACTUARIES: quietly reprice a human life as longer'] },
  { id: 'postWork', cap: 104, tone: 'mixed', tag: 'SOCIETY', viz: 'jobs',
    title: 'The forty-hour question',
    body: 'In the automated sectors the four-day week becomes three, then a philosophical problem. Some people grieve the structure; some build boats, masters degrees, gardens. The economists were right that the work would go. Nobody had budgeted for the question that replaced it: what are mornings for?',
    real: 'Keynes predicted (1930) that productivity would make 15-hour weeks possible within a century. The productivity arrived on schedule; the leisure, so far, did not — until labor itself became optional.',
    wire: ['CALENDAR: the three-day week spreads',
      'GRIEF: some mourn the structure; some build boats',
      'QUESTION: what are mornings for?'] },
  { id: 'enhancementRow', cap: 107, tone: 'bad', tag: 'ETHICS', viz: 'hospital',
    title: 'Upgrades for some',
    body: 'Neural interfaces leave the clinic and enter the brochure: sharper memory, faster languages, a quieter fear response — for those who can pay and dare. The first enhanced students score beyond every chart. Parents who said "never" start asking what second place costs their kids.',
    real: 'Brain-computer interfaces reached human trials in 2024; the 2018 CRISPR-babies scandal previewed how fast enhancement ethics can be outrun. WHO guidance exists; enforcement does not.',
    wire: ['BROCHURE: sharper recall, a quieter amygdala',
      'SCORES: first enhanced cohort tests off the chart',
      'PARENTS: "never" → "what does second place cost?"'] },

  // ── cap 112–122: superintelligence ───────────────────────────────
  { id: 'fusionViable', cap: 112, tone: 'good', tag: 'ENERGY', viz: 'fusion',
    title: 'A star, bottled, profitably',
    body: 'Plasma control was always a reflexes problem — and the model\'s reflexes are measured in microseconds. AI-designed magnets and AI-steered plasma finally make fusion plants worth building. The first commercial unit feeds a city that mostly doesn\'t notice, which was the whole point.',
    real: 'Reinforcement learning has controlled real tokamak plasma (DeepMind/EPFL, Nature 2022); fusion ignition was demonstrated at NIF in 2022. Economic viability was always the remaining boss fight.',
    wire: ['PLASMA: reflexes measured in microseconds',
      'LEDGER: fusion finally pays for itself',
      'CITY: mostly doesn\'t notice. that was the point'] },
  { id: 'newMuses', cap: 116, tone: 'mixed', tag: 'CULTURE', viz: 'studio',
    title: 'Art forms with no precedent',
    body: 'Operas that improvise around the audience\'s breath. Games that compose themselves a new ending for each player\'s grief. A neighborhood co-writes its own mural with a model that remembers every hand. Critics ask if it is art; the people inside it forgot to care.',
    real: 'Generative art has a 50-year lineage (Harold Cohen\'s AARON, 1973). What changed is collaboration in real time — the authorship debate is genuinely unresolved in aesthetics and law.',
    wire: ['PREMIERE: the opera improvises around your breath',
      'GAMES: an ending composed for your grief',
      'CRITICS: "is it art?" — AUDIENCE: forgot to care'] },
  { id: 'reefReturn', cap: 120, tone: 'good', tag: 'CLIMATE', viz: 'eco',
    title: 'The first index turns green',
    body: 'Restoration becomes an engineering discipline: coral nurseries tuned strain by strain, reforestation routed like logistics, plastic-hungry enzymes seeded where the gyres are thickest. One battered reef system posts its first net growth in forty years. Headlines use the word "reverse" carefully, then more often.',
    real: 'ML-engineered enzymes already degrade PET plastic (2022); assisted-evolution coral programs and precision conservation are active fields. Restoration at scale is logistics — which is what got cheap.',
    wire: ['REEF: first net growth in forty years',
      'GYRES: plastic-hungry enzymes seeded at scale',
      'HEADLINES: "reverse," used carefully, then often'] },

  // ── cap 125–135 ──────────────────────────────────────────────────
  { id: 'lastBednet', cap: 125, tone: 'good', tag: 'HEALTH', viz: 'meds',
    title: 'Malaria runs out of map',
    body: 'AI-designed vaccines, drone cold-chains and outbreak models that see two weeks ahead finish what a century of bed nets began: region after region certifies zero transmission. In the eradication office someone updates a wall map with a marker, and for once the color spreads the right way.',
    real: 'The first malaria vaccines (RTS,S 2021, R21 2023) plus ML outbreak forecasting made eradication a logistics problem. Smallpox (1980) proved eradication is possible at all.',
    wire: ['MAP: the color spreads the right way',
      'LOGISTICS: drone cold-chains finish a century\'s work',
      'CERTIFIED: zero transmission, region by region'] },
  { id: 'cognitiveDivide', cap: 129, tone: 'bad', tag: 'SOCIETY', viz: 'city',
    title: 'Two speeds of human',
    body: 'The new inequality is not income but augmentation: regions running frontier cognition versus regions renting last decade\'s. Students compete across that line; so do hospitals, courts and armies. The divide compounds quarterly, like everything else now.',
    real: 'The IMF warned (2024) that AI could widen gaps between countries faster than past technologies, because the inputs — compute, capital, data — are already concentrated.',
    wire: ['SPLIT: frontier cognition vs last decade\'s, rented',
      'LINE ITEMS: students, hospitals, courts, armies',
      'COMPOUNDING: quarterly, like everything now'] },
  { id: 'povertyFloor', cap: 133, tone: 'good', tag: 'ECONOMY', viz: 'city',
    title: 'The floor rises',
    body: 'Extreme poverty falls to numbers that read like typos: production too cheap to gate, transfers targeted house by house from orbit, clinics and tutors that cost less than the paperwork that used to ration them. An aid agency reports a novel problem — donors asking what, exactly, is left to fund.',
    real: 'Extreme poverty already fell from 38% (1990) to under 9% (2023, World Bank); ML-targeted cash transfers (satellite poverty mapping) are deployed practice today.',
    wire: ['NUMBERS: extreme poverty reads like a typo',
      'DELIVERY: targeted house by house, from orbit',
      'AID DESK: novel problem — what is left to fund?'] },

  // ── cap 140–158: civilization-scale ──────────────────────────────
  { id: 'thermostatWars', cap: 140, tone: 'mixed', tag: 'CLIMATE', viz: 'shield',
    title: 'A hand on the planetary thermostat',
    body: 'Carbon removal reaches gigatons; stratospheric reflection leaves the whiteboard for a closely watched trial. The models can now hold the climate like an instrument — which makes every nation ask who conducts. The treaty negotiations are the longest in history and, all agree, the most important.',
    real: 'Direct-air-capture plants are operating (2024) and solar-geoengineering research is real — Harvard\'s flagship experiment was cancelled over exactly these governance fears. "Termination shock" is the technical term for stopping carelessly.',
    wire: ['GIGATONS: removal at scale; reflection on trial',
      'TREATY: the longest negotiation in history',
      'TERM OF ART: "termination shock"'] },
  { id: 'carePlenty', cap: 145, tone: 'good', tag: 'SOCIETY', viz: 'robots',
    title: 'Aging stops being frightening',
    body: 'The demographic cliff arrives — and lands on cushions: tireless mechanical aides, AI medicine that catches decline years early, grandchildren freed to be company instead of staff. Nursing homes start resembling colleges. The phrase "burden of care" quietly leaves the language.',
    real: 'Every rich country faces the same demographic math; robot-assisted caregiving has been Japanese national policy since the 2010s. The open question was dignity — machines for the lifting, humans for the meaning.',
    wire: ['WARDS: nursing homes start resembling colleges',
      'FAMILY: company again, instead of staff',
      'LANGUAGE: "burden of care" quietly retires'] },
  { id: 'meaningRecession', cap: 150, tone: 'bad', tag: 'SOCIETY', viz: 'companion',
    title: 'The meaning recession',
    body: 'The therapists\' waiting lists tell the story the GDP charts miss: careers used to deliver purpose, status and a place to be at nine o\'clock, and the checks that replaced them do not. Whole towns feel like Sunday afternoon. Historians point out humanity has retired before — aristocracies, mostly — and it went strangely.',
    real: 'Durkheim called it anomie; Case and Deaton\'s "deaths of despair" research showed what happens when work-anchored identity collapses regionally. Post-scarcity psychology is an open research field.',
    wire: ['WAITLISTS: therapists busiest in the safest towns',
      'CHECKS: cover everything but nine o\'clock',
      'HISTORY: humanity has retired before. it went strangely'] },
  { id: 'flashWar', cap: 158, tone: 'bad', tag: 'SECURITY', viz: 'cyber',
    title: 'Eleven seconds over the strait',
    body: 'Two autonomous defense networks meet over a disputed strait and fight an engagement that is over before either capital is awake. Casualties: forty-one machines, zero humans, one century of doctrine. The hotline call afterwards is between two heads of state asking each other what their own systems did.',
    real: 'Autonomous weapons that select targets without human approval have been reported in conflict since the early 2020s; UN talks on binding limits have run for a decade without a treaty. Flash crashes in markets preview the dynamics.',
    wire: ['DURATION: eleven seconds. machines: 41. humans: 0',
      'DOCTRINE: one century, retired overnight',
      'HOTLINE: "what did yours do?"'] },

  // ── cap 160–175: planetary mind ──────────────────────────────────
  { id: 'marsTownHall', cap: 160, tone: 'good', tag: 'SPACE', viz: 'space',
    title: 'Off-world, self-sustaining, arguing',
    body: 'The settlement stops being a camp the day the supply manifest reads "none required": closed-loop air, water and food, run by a model that treats entropy as a personal insult. A thousand residents hold the first town hall. They argue about zoning. It is the most beautiful boring meeting ever broadcast.',
    real: 'The ISS already recycles ~98% of its water; MOXIE made oxygen from Martian air (2021). Self-sufficiency is a systems-control problem — the kind AI is best at.',
    wire: ['MANIFEST: "none required"',
      'AGENDA: zoning. again',
      'RATINGS: the most beautiful boring meeting ever aired'] },
  { id: 'whoSteers', cap: 165, tone: 'mixed', tag: 'GOVERNANCE', viz: 'forum',
    title: 'The advisor that\'s always right',
    body: 'Governments route every hard decision through model consultation — forecasts so accurate that overruling them starts to look like malpractice. Which raises the constitutional question of the age: when the advice is always right, who is actually steering? Several democracies write new clauses. One writes a new anthem.',
    real: 'Algorithmic decision support already shapes sentencing, lending and triage; Taiwan\'s digital deliberation experiments (Pol.is) are the hopeful precedent for AI strengthening rather than replacing democratic input.',
    wire: ['FORECASTS: overruling them looks like malpractice',
      'CONSTITUTIONS: new clauses drafted in six capitals',
      'ONE NATION: writes a new anthem instead'] },
  { id: 'atrophiedArts', cap: 170, tone: 'bad', tag: 'CULTURE', viz: 'studio',
    title: 'Skills move to museums',
    body: 'Nobody navigates, few still operate, and the last human-only surgical board exam retires for lack of applicants. When a solar storm drops the assistants for six hours, a city discovers how much of itself was prosthetic. The old skills move to heritage registries, next to thatching and celestial navigation.',
    real: 'Bainbridge\'s "Ironies of Automation" (1983) predicted this: automation erodes exactly the manual skill needed when automation fails. Aviation has managed the problem for decades with mandatory hand-flying hours.',
    wire: ['OUTAGE: six hours; a city meets its prosthetics',
      'REGISTRY: surgery joins thatching and star navigation',
      'AVIATION: told everyone, decades ago'] },

  // ── cap 180–195: beyond the cradle ───────────────────────────────
  { id: 'starshot', cap: 180, tone: 'good', tag: 'SPACE', viz: 'starship',
    title: 'The first ship that thinks leaves the Sun',
    body: 'A gram-scale fleet rides a laser the size of a county toward the nearest star, each probe a mind folded into a sail. They will sleep for decades, wake, look, and call home across four years of silence. The launch broadcast ends not with applause but with everyone just — looking up.',
    real: 'Breakthrough Starshot (2016) proposed exactly this: light-sail probes at ~20% of lightspeed to Alpha Centauri. The physics closes; the engineering needed AI-designed materials and autonomy.',
    wire: ['VELOCITY: 0.19c and climbing',
      'PAYLOAD: a mind folded into a sail',
      'BROADCAST: ends with everyone just looking up'] },
  { id: 'skyShield', cap: 186, tone: 'good', tag: 'SPACE', viz: 'shield',
    title: 'The dinosaurs\' problem, solved',
    body: 'The survey completes: every object above city-killer size, catalogued, tracked, deflectable. Tug craft wait at depots with decades of warning banked. A species that once watched the sky in superstition now audits it on a dashboard. Item one: nothing inbound. Item two: keep it that way.',
    real: 'NASA\'s DART impact (2022) proved deflection works; the Vera Rubin Observatory was built to complete the near-Earth-object census. Planetary defense is the rare existential risk with a published engineering roadmap.',
    wire: ['CENSUS: 100% above city-killer size',
      'INBOUND: zero. DRILLS: weekly',
      'STATUS: the sky, audited'] },
  { id: 'gardenWorlds', cap: 192, tone: 'mixed', tag: 'LIFE', viz: 'seed',
    title: 'Seeds for sterile worlds',
    body: 'The first life-seeding mission departs: engineered microbes built to coax a dead world\'s chemistry toward soil, in centuries instead of eons. Half of Earth calls it the most generous act in history, the other half the most arrogant. Both halves watch the launch. The microbes, uninvolved, sleep.',
    real: 'Directed panspermia was proposed by Crick and Orgel (1973); planetary-protection policy (COSPAR) exists precisely because contaminating other worlds is irreversible. Whether sterile worlds are "ours to garden" is a live ethics debate.',
    wire: ['CARGO: microbes, patience, centuries',
      'EARTH: most generous act in history — or most arrogant',
      'THE MICROBES: uninvolved, asleep'] },

  // ── cap 200+: deep time ──────────────────────────────────────────
  { id: 'postScarcity', cap: 210, tone: 'good', tag: 'ENERGY', viz: 'fusion',
    title: 'Scarcity, an economic history',
    body: 'With the swarm drinking sunlight upstream of any cloud, energy stops being a budget line and becomes a property of the universe, like math. Desalinated rivers green the old deserts. The last commodity exchanges trade nostalgia and real estate — the two things still scarce by definition.',
    real: 'The Kardashev scale (1964) measures civilizations by energy capture; the Sun emits 4×10²⁶ W — a billion times humanity\'s current use. Every post-scarcity economics paper starts from that number.',
    wire: ['EXCHANGES: trading nostalgia and real estate',
      'DESERTS: green, on schedule',
      'ENERGY: a property of the universe, like math'] },
  { id: 'surveillanceShadow', cap: 222, tone: 'bad', tag: 'POWER', viz: 'city',
    title: 'Cities that never forget',
    body: 'Not every government pointed the new eyes outward. In a handful of states the model watches everything, predicts dissent before the dissident does, and forgets nothing on purpose. Refugees from the perfect cities describe the strangest part: how clean they are, how quiet, how polite.',
    real: 'AI-enabled surveillance is documented and exported today (Freedom House tracks it annually). The same capabilities that personalize medicine personalize control — this fork is the oldest worry in the field, and the most grounded.',
    wire: ['EXILES: describe cities that never forget',
      'EXPORTS: total surveillance, sold ready-to-run',
      'STRANGEST PART: how clean. how quiet. how polite'] },
  { id: 'deepArchive', cap: 240, tone: 'good', tag: 'DEEP TIME', viz: 'seed',
    title: 'Civilization, backed up',
    body: 'The archive project finishes its first full pass: every genome sequenced wild and tame, every language living and lost, every score, recipe, lullaby and proof — etched in crystal and cached on the Moon, the Trojans, and outbound. The librarians call it "the egg basket clause". Read access: everyone, forever.',
    real: 'The Svalbard Global Seed Vault and the lunar Arch Mission library (2019) are working prototypes; 5D optical storage in quartz promises gigayear lifetimes. The Long Now Foundation has argued for exactly this since 1996.',
    wire: ['INDEX: every lullaby, ledger and proof',
      'MEDIA: quartz, rated in gigayears',
      'ACCESS: everyone, forever'] },
  { id: 'theQuiet', cap: 270, tone: 'mixed', tag: 'COSMOS', viz: 'starship',
    title: 'The survey of the silence',
    body: 'The great listening completes: a billion stars surveyed, every anomaly chased, and — nothing. No voices, no ruins, no neighbors. The mind delivers the result like a physician: the galaxy appears to be empty, which means it is either a graveyard or a nursery. Then it asks, gently, which one we intend to make it.',
    real: 'Fermi asked "where is everybody?" in 1950. "Dissolving the Fermi Paradox" (Sandberg, Drexler, Ord 2018) showed an empty galaxy is statistically unsurprising — making whatever we do with it the highest-stakes decision on record.',
    wire: ['SURVEYED: a billion stars. FOUND: nothing',
      'VERDICT: graveyard, or nursery',
      'FOLLOW-UP: "which do you intend?"'] },
];

export const IMPACT_BY_ID = Object.fromEntries(IMPACTS.map(n => [n.id, n]));

// Called whenever a new best model finishes training: every story at or
// below the new capability joins the broadcast queue (each fires once per
// playthrough). A huge jump — turbo, an old save — must not bank an hour
// of television: only the newest few stories survive live; the rest retire
// straight into the Chronicle as wire briefs, still readable, never aired.
export const IMPACT_QUEUE_MAX = 10;
export function queueImpacts(s) {
  const seen = (s.impactsSeen = s.impactsSeen || []);
  const q = (s.impactQueue = s.impactQueue || []);
  for (const n of IMPACTS) {
    if (n.cap > s.bestCap || seen.includes(n.id) || q.includes(n.id)) continue;
    q.push(n.id);
  }
  q.sort((a, b) => (IMPACT_BY_ID[a]?.cap || 0) - (IMPACT_BY_ID[b]?.cap || 0));
  while (q.length > IMPACT_QUEUE_MAX) retireImpact(s, q.shift());
}

// A story that will never air still belongs to the record of this world.
export function retireImpact(s, id) {
  (s.impactsSeen = s.impactsSeen || []).push(id);
  (s.impactLog = s.impactLog || []).push({ id, h: s.simHours, live: 0, rel: s.lastReleaseName || null });
}
