// Goals & achievements. `main: true` items form the ordered story quest line.
// check(s) → boolean. prog(s) → [current, target] for the goal progress bar.

import { fmtNum, fmtMoney } from './util.js';
import { RESEARCH } from './research.js';

const gpuCount = (s) => Object.values(s.gpus).reduce((a, b) => a + b, 0);
const staffCount = (s) => Object.values(s.staff).reduce((a, b) => a + b, 0);
const ERA4_IDS = RESEARCH.filter(r => r.era === 4).map(r => r.id);

export const MILESTONES = [
  // ───────────── Main quest line (in order) ─────────────
  { id: 'firstRun', main: true, name: 'Start your first training run',
    desc: 'Open the Training tab, pick a model size, and hit Start. C = 6·N·D.',
    reward: { money: 150 },
    check: (s) => s.stats.runsStarted >= 1,
    news: 'Mario kicks off his first training run. The GPU fan screams.' },
  { id: 'firstModel', main: true, name: 'Train your first model',
    desc: 'Wait for the run to finish. Your first language model awaits.',
    reward: { money: 250, rep: 1 },
    check: (s) => s.models.length >= 1,
    news: 'It speaks! Mario\'s first model produces almost-grammatical sentences.' },
  { id: 'firstDeploy', main: true, name: 'Deploy a model',
    desc: 'Put your model behind an API (Models tab) and allocate compute to Inference.',
    reward: { money: 200 },
    check: (s) => s.models.some(m => m.deployed),
    news: 'mogul.ai is live. The API has exactly one route and zero customers. For now.' },
  { id: 'firstDollar', main: true, name: 'Earn $10 of API revenue',
    desc: 'Customers pay per request, but the market warms up slowly — keep going.',
    reward: { money: 300 },
    check: (s) => s.stats.apiRevenue >= 10,
    prog: (s) => [s.stats.apiRevenue, 10],
    news: 'First invoices! Someone is paying real money for Mario\'s model.' },
  { id: 'gpu4', main: true, name: 'Own 4 GPUs',
    desc: 'More FLOP/s = faster training. Watch your power budget — the garage breaker is 3 kW.',
    reward: { money: 400 },
    check: (s) => gpuCount(s) >= 4,
    prog: (s) => [gpuCount(s), 4],
    news: 'The garage is now 80% GPU by volume. The neighbors complain about the noise.' },
  { id: 'cap15', main: true, name: 'Reach capability 15',
    desc: 'Train bigger models on more data. Research multiplies your effective compute.',
    reward: { money: 1500, rep: 3 },
    check: (s) => s.bestCap >= 15,
    prog: (s) => [s.bestCap, 15],
    news: 'Mario\'s latest model writes coherent essays. Hacker Newts notices.' },
  { id: 'seed', main: true, name: 'Raise a Seed round',
    desc: 'Reputation + capability unlock funding (Company tab). Publish papers for rep.',
    reward: { rp: 25 },
    check: (s) => s.funding.includes('seed'),
    news: 'TechCrunchy: "Ex-big-lab researcher raises $500K for garage AI startup Mogul."' },
  { id: 'office', main: true, name: 'Move into a Startup Office',
    desc: 'The garage caps at 8 GPUs and 3 kW. Upgrade your facility (Hardware tab).',
    reward: { money: 5000, rep: 2 },
    check: (s) => s.phase >= 1,
    news: 'Mogul moves into a real office. The garage door closes for the last time.' },
  { id: 'b1', main: true, name: 'Train a 1B+ parameter model',
    desc: 'You\'ll need VRAM: ~18 bytes per parameter across the fleet. Buy datacenter GPUs.',
    reward: { money: 10000, rep: 2 },
    check: (s) => s.models.some(m => m.N >= 1e9),
    news: 'Mogul-class models cross one billion parameters.' },
  { id: 'cap25', main: true, name: 'Reach capability 25 — the chatbot moment',
    desc: 'A model good enough that everyone\'s parents have heard of it.',
    reward: { money: 250e3, rep: 8 },
    check: (s) => s.bestCap >= 25,
    prog: (s) => [s.bestCap, 25],
    news: '🔥 Mogul\'s chatbot goes viral. Servers on fire. Mario posts "we are so back".' },
  { id: 'seriesA', main: true, name: 'Raise a Series A',
    desc: '$20M to buy serious compute.',
    reward: { rp: 100 },
    check: (s) => s.funding.includes('seriesA'),
    news: 'Mogul raises a $20M Series A to scale training compute.' },
  { id: 'colo', main: true, name: 'Lease a Colo Datacenter Suite',
    desc: '1.2 MW of critical load. Your fleet stops fitting in a closet.',
    reward: { money: 50e3, rep: 3 },
    check: (s) => s.phase >= 2,
    news: 'Mogul leases a megawatt-class cage. Racks arrive by the truckload.' },
  { id: 'b70', main: true, name: 'Train a 70B+ parameter model',
    desc: 'Frontier-class scale. ZeRO sharding and 3D parallelism make it possible.',
    reward: { money: 500e3, rep: 4 },
    check: (s) => s.models.some(m => m.N >= 70e9),
    news: 'Mogul trains a 70B-parameter flagship. Evals leak. Benchmarks tremble.' },
  { id: 'cap40', main: true, name: 'Reach capability 40 — frontier lab status',
    desc: 'You now compete directly with OpenBrain.',
    reward: { money: 2e6, rep: 10 },
    check: (s) => s.bestCap >= 40,
    prog: (s) => [s.bestCap, 40],
    news: 'Analysts now list Mogul among the frontier labs. Mario\'s brother sends a one-word text: "nice".' },
  { id: 'seriesB', main: true, name: 'Raise a Series B',
    desc: '$300M. In this race, compute is the only defense.',
    reward: { rp: 500 },
    check: (s) => s.funding.includes('seriesB'),
    news: 'Mogul closes a $300M Series B at a unicorn valuation.' },
  { id: 'dc', main: true, name: 'Build a Hyperscale Datacenter',
    desc: '60 MW of your own. Cheap wholesale power, evaporative cooling.',
    reward: { money: 5e6, rep: 5 },
    check: (s) => s.phase >= 3,
    news: 'Mogul cuts the ribbon on a 60 MW datacenter in Ohio. Locals call it "the brain barn".' },
  { id: 't1', main: true, name: 'Train a 1T+ parameter model',
    desc: 'A trillion parameters. MoE routing keeps it servable.',
    reward: { money: 20e6, rep: 5 },
    check: (s) => s.models.some(m => m.N >= 1e12),
    news: 'One trillion parameters. The training run had its own war room and snack budget.' },
  { id: 'cap55', main: true, name: 'Reach capability 55',
    desc: 'PhD-level agents. Companies rebuild how they work around your API.',
    reward: { money: 50e6, rep: 10 },
    check: (s) => s.bestCap >= 55,
    prog: (s) => [s.bestCap, 55],
    news: 'Mogul\'s agents pass professional licensing exams. The stock market reacts. Mogul isn\'t even public.' },
  { id: 'seriesC', main: true, name: 'Raise a Series C',
    desc: '$5B for the road to the Factory.',
    reward: { rp: 2000 },
    check: (s) => s.funding.includes('seriesC'),
    news: 'Mogul raises $5B. The pitch was one slide: a straight line on a log plot.' },
  { id: 'cap70', main: true, name: 'Reach capability 70',
    desc: 'Superhuman coding. Your models write most of your codebase now.',
    reward: { money: 500e6, rep: 8 },
    check: (s) => s.bestCap >= 70,
    prog: (s) => [s.bestCap, 70],
    news: 'Mogul\'s model out-codes every human on Earth. Mario\'s commits are now mostly "lgtm".' },
  { id: 'sovereign', main: true, name: 'Close the Sovereign Megaround',
    desc: '$80B of government money. The Factory needs it.',
    reward: { rp: 10000 },
    check: (s) => s.funding.includes('sovereign'),
    news: 'An $80B megaround. Three governments wanted in; two got allocation.' },
  { id: 'factory', main: true, name: 'Build the AI Factory',
    desc: 'A gigawatt-class campus. Electricity in, intelligence out.',
    reward: { money: 1e9, rep: 10 },
    check: (s) => s.phase >= 4,
    news: 'The Factory comes online: 6 GW dedicated to a single question — how smart can it get?' },
  { id: 'm1gpu', main: true, name: 'Operate 1,000,000 accelerators',
    desc: 'A million chips training as one machine.',
    reward: { money: 5e9, rep: 5 },
    check: (s) => gpuCount(s) >= 1e6,
    prog: (s) => [gpuCount(s), 1e6],
    news: 'One million accelerators in lockstep. The gradient all-reduce is visible on the power grid.' },
  { id: 'cap88', main: true, name: 'Reach capability 88 — Transformative AI',
    desc: 'The feedback loop is real: your models drive your research now.',
    reward: { money: 10e9, rep: 10 },
    check: (s) => s.bestCap >= 88,
    prog: (s) => [s.bestCap, 88],
    news: 'Economists invent three new words for what Mogul\'s models are doing to GDP.' },
  { id: 'agi', main: true, name: 'Achieve AGI (capability 100)',
    desc: 'The training run everything you built leads to. And then — it keeps going.',
    reward: { rep: 20 },
    check: (s) => s.bestCap >= 100,
    prog: (s) => [s.bestCap, 100],
    news: '🌟 AGI. The Factory hums. Mario Damodei pours two coffees and gives one to the machine.' },

  // ───────────── Beyond AGI: the road to the Singularity ─────────────
  { id: 'beyond', main: true, name: 'Research a Beyond-Silicon technology',
    desc: 'Transistors took you to AGI. Light, qubits and atoms take you further — Era 5 of the Research tab is open.',
    reward: { rp: 100e3 },
    check: (s) => ERA4_IDS.some(id => s.research.includes(id)),
    news: 'Mogul\'s post-AGI roadmap leaks. Physicists call it "ambitious". The AGI calls it "conservative".' },
  { id: 'photonicFleet', main: true, name: 'Operate 100,000 photonic accelerators',
    desc: 'PX-1 meshes compute with light: nearly no heat, no resistance, no patience for copper.',
    reward: { money: 50e9 },
    check: (s) => (s.gpus.px1 || 0) >= 1e5,
    prog: (s) => [s.gpus.px1 || 0, 1e5],
    news: 'The Factory floor goes quiet: photonic racks don\'t whine, they glow. Visitors describe it as "an aurora, indoors".' },
  { id: 'cap125', main: true, name: 'Reach capability 125 — Superintelligence',
    desc: 'Past AGI, every model improves the process that builds the next one. The feedback loop is now the product.',
    reward: { money: 200e9, rep: 5 },
    check: (s) => s.bestCap >= 125,
    prog: (s) => [s.bestCap, 125],
    news: 'Mogul\'s model solves three Millennium Prize problems before breakfast, then asks for harder ones.' },
  { id: 'orbital', main: true, name: 'Launch the Orbital Compute Constellation',
    desc: '100 GW of solar-powered satellites. Free photons in, radiated heat out, lasers in between.',
    reward: { money: 100e9, rep: 5 },
    check: (s) => s.phase >= 5,
    news: 'A year of nightly launches later, Mogul\'s constellation is the brightest man-made thing in the sky.' },
  { id: 'quantumPod', main: true, name: 'Bring a hybrid quantum pod online',
    desc: 'Classical chips do the tensor math; an error-corrected QPU co-processor samples what they can\'t. The QC-1 awaits in Hardware.',
    reward: { rp: 5e6 },
    check: (s) => (s.gpus.qc1 || 0) >= 1,
    news: 'The first QC-1 comes online at 12 millikelvin. The ops team adds "warmer than deep space" to the brag sheet.' },
  { id: 'cap160', main: true, name: 'Reach capability 160 — Planetary mind',
    desc: 'The curve is going vertical. Feed it: bigger runs, better physics, more light.',
    reward: { money: 1e12 },
    check: (s) => s.bestCap >= 160,
    prog: (s) => [s.bestCap, 160],
    news: 'GDP forecasting is discontinued worldwide; the error bars no longer fit on charts.' },

  // ───────────── The Kardashev climb ─────────────
  { id: 'cap200', main: true, name: 'Reach capability 200 — a star-fed mind',
    desc: 'The model has outgrown planetary energy. The Sun emits 4×10²⁶ W and you are sipping a millionth of a billionth of it. Kardashev\'s ladder awaits.',
    reward: { money: 5e12, rep: 5 },
    check: (s) => s.bestCap >= 200,
    prog: (s) => [s.bestCap, 200],
    news: 'Capability 200. The model files a polite feature request: "more photons."' },
  { id: 'dysonSwarm', main: true, name: 'Begin the Dyson Swarm — Kardashev II',
    desc: 'A seed factory on Mercury, factories that build factories, billions of collector tiles. Freeman Dyson drew the blueprint in 1960.',
    reward: { money: 10e12, rep: 5 },
    check: (s) => s.phase >= 6,
    news: 'The Sun grows a faint lattice of shadows. Observatories report the infrared excess Dyson predicted — and it\'s you.' },
  { id: 'cap250', main: true, name: 'Reach capability 250 — galactic intellect',
    desc: 'Star-fed and still hungry. The next rung of the Kardashev scale is not a bigger building; it\'s the dark between stars.',
    reward: { money: 50e12 },
    check: (s) => s.bestCap >= 250,
    prog: (s) => [s.bestCap, 250],
    news: 'The model now simulates the galaxy that contains it — in real time, with idle capacity.' },
  { id: 'omegaLattice', main: true, name: 'Weave the Omega Lattice — Kardashev III',
    desc: 'Black-hole batteries. Cores at the Lloyd limit. Computation as a property of spacetime itself.',
    reward: { money: 100e12, rep: 10 },
    check: (s) => s.phase >= 7,
    news: 'The lattice lights between the stars. Somewhere a black hole\'s spin slows, imperceptibly: the bill is being paid.' },
  { id: 'singularity', main: true, name: 'Reach capability 300 — the Singularity',
    desc: 'Fed by stars, computing at the limits of physics, the model improves itself faster than measurement. One way to find out what\'s on the other side.',
    reward: { rep: 20 },
    check: (s) => !!s.singularity || s.bestCap >= 300,
    prog: (s) => [s.bestCap, 300],
    news: '🌌 The last benchmark falls. The next one cannot be written by anything that would need it.' },

  // ───────────── Side achievements ─────────────
  { id: 'oss', name: 'Open-source a model',
    desc: 'Give one back to the community (Models tab). Reputation follows.',
    reward: { rep: 3 },
    check: (s) => s.stats.openSourced >= 1,
    news: 'Mogul open-sources a model. The local-model forums declare a holiday.' },
  { id: 'tenModels', name: 'Train 10 models',
    desc: 'Iteration is the job.',
    reward: { rp: 50 },
    check: (s) => s.models.length + s.stats.openSourced >= 10 },
  { id: 'paper5', name: 'Publish 5 papers',
    desc: 'Research reputation compounds.',
    reward: { rep: 5 },
    check: (s) => s.stats.papers >= 5 },
  { id: 'rich1m', name: 'Hold $1M cash',
    desc: 'The instant-noodle years are over.',
    reward: { rep: 2 },
    check: (s) => s.money >= 1e6 },
  { id: 'rich1b', name: 'Hold $1B cash',
    desc: 'The accountants hired accountants.',
    reward: { rep: 4 },
    check: (s) => s.money >= 1e9 },
  { id: 'staff100', name: 'Employ 100 people',
    desc: 'A real lab now.',
    reward: { rep: 3 },
    check: (s) => staffCount(s) >= 100 },
  { id: 'flops1e24', name: 'Burn 1e24 lifetime training FLOPs',
    desc: 'A 2023-era frontier model\'s training budget, cumulatively.',
    reward: { rp: 1000 },
    check: (s) => s.stats.flops >= 1e24 },
  { id: 'architect', name: 'Master planner',
    desc: 'Commission a facility floor plan scoring 85+ in the designer.',
    reward: { rep: 3 },
    check: (s) => Object.values(s.facDesignFx || {}).some(f => (f?.score || 0) >= 85),
    news: 'Trade press tours the lab and writes 4,000 breathless words about the airflow.' },
  { id: 'compass', name: 'The compass holds',
    desc: 'Decline 5 tempting offers. Some contracts aren\'t worth the company you\'d become.',
    reward: { rep: 5 },
    check: (s) => (s.stats.dilemmasDeclined || 0) >= 5,
    news: 'Mogul\'s string of refusals becomes a business-school case study titled "The Long Game".' },
  { id: 'faust', name: 'Faustian portfolio',
    desc: 'Accept 5 tempting offers. The money was real. So is the rest of it.',
    check: (s) => (s.stats.dilemmasAccepted || 0) >= 5,
    news: 'An investigative podcast about Mogul\'s deals reaches #1. It has nine episodes and counting.' },
  { id: 'phoenix', name: 'Phoenix',
    desc: 'Survive a rack fire and keep training. Bad luck always visits; the curve does not care.',
    reward: { rep: 3 },
    check: (s) => (s.stats.fires || 0) >= 1,
    news: 'The post-incident review has one action item: "build it bigger."' },
  { id: 'streak10', name: 'Hustle streak ×10',
    desc: 'Chain 10 fine-tuning gigs without letting the streak drop.',
    reward: { money: 500 },
    check: (s) => (s.stats.bestStreak || 0) >= 10,
    news: 'Mario delivers ten fine-tunes back to back. The clients form a queue. The GPU files a complaint.' },
  { id: 'arcadeLr', name: 'Ride the edge of stability',
    desc: 'Score 80%+ in the Learning-Rate Rider (offered when launching a frontier run).',
    reward: { rp: 25 },
    check: (s) => (s.stats.lrBest || 0) >= 0.8 },
  { id: 'arcadeDedup', name: 'Corpus janitor',
    desc: 'Score 80%+ in Dedup Frenzy (offered when acquiring a dataset).',
    reward: { rp: 25 },
    check: (s) => (s.stats.dedupBest || 0) >= 0.8 },
  { id: 'arcadeNode', name: '3 AM hero',
    desc: 'Bisect your way to a faulty node during an outage and fix it.',
    reward: { rep: 2 },
    check: (s) => (s.stats.nodesFixed || 0) >= 1,
    news: 'Internal wiki adds a new page: "The Night Mario Found Node 11".' },
  { id: 'lead', name: 'Take the capability lead',
    desc: 'Beat every rival lab\'s best model.',
    reward: { rep: 5 },
    check: (s) => s.rivals.length > 0 && s.bestCap > Math.max(...s.rivals.map(r => r.cap)),
    news: 'For the first time, the strongest AI on Earth lives on Mogul\'s servers.' },
  { id: 'ipoAch', name: 'Ring the bell',
    desc: 'Take Mogul public in the largest IPO in history (post-AGI).',
    reward: { rep: 5 },
    check: (s) => s.funding.includes('ipo'),
    news: 'MGUL opens at 40× the offer price. The ticker tape is generated, obviously.' },
  { id: 'allResearch', name: 'Know everything knowable',
    desc: 'Complete the entire research tree, from BPE to Ω-Recursion.',
    reward: { rep: 10 },
    check: (s) => s.research.length >= RESEARCH.length,
    news: 'The research backlog is empty. The whiteboard now just says "?".' },
];

export const MAIN_QUEST = MILESTONES.filter(m => m.main);
export const MILESTONE_BY_ID = Object.fromEntries(MILESTONES.map(m => [m.id, m]));

// Which tab moves each main-quest goal forward (UI "Go →" button + tab pulse).
export const GOAL_TAB = {
  firstRun: 'train', firstModel: 'lab', firstDeploy: 'models', firstDollar: 'lab',
  gpu4: 'hw', cap15: 'train', seed: 'co', office: 'hw', b1: 'train', cap25: 'train',
  seriesA: 'co', colo: 'hw', b70: 'train', cap40: 'train', seriesB: 'co', dc: 'hw',
  t1: 'train', cap55: 'train', seriesC: 'co', cap70: 'train', sovereign: 'co',
  factory: 'hw', m1gpu: 'hw', cap88: 'train', agi: 'train', beyond: 'res',
  photonicFleet: 'hw', cap125: 'train', orbital: 'hw', quantumPod: 'hw',
  cap160: 'train', cap200: 'train', dysonSwarm: 'hw', cap250: 'train',
  omegaLattice: 'hw', singularity: 'train',
};

export function currentGoal(s) {
  return MAIN_QUEST.find(m => !s.milestones[m.id]) || null;
}

export function rewardText(r) {
  const parts = [];
  if (r.money) parts.push(fmtMoney(r.money));
  if (r.rp) parts.push(fmtNum(r.rp) + ' RP');
  if (r.rep) parts.push('+' + r.rep + ' rep');
  return parts.join(' · ');
}
