// Research tree. Effects:
//   algo: ×N effective-compute multiplier (algorithmic efficiency)
//   mfu: +N model-FLOPs-utilization
//   dataQ: ×N data quality multiplier
//   memEff: ×N trainable-params-per-VRAM multiplier
//   infEff: ÷N serving cost per request
//   revMult / demandMult: ×N revenue price / market demand
//   gigMult: ×N freelance gig pay
//   rpMult: ×N research point generation
//   powerMult: ×N electricity price (<1 is cheaper)
//   maxRuns: +N concurrent training runs
//   unlock: feature flag ('mx1' gpu, 'synthData' dataset, …)
// era = min facility phase required. reqCap = min best-model capability.

export const RESEARCH = [
  // ── Era 0: Foundations (garage) ────────────────────────────────
  { id: 'bpe', era: 0, rp: 8, name: 'Better Tokenization',
    fx: { algo: 1.12 },
    desc: 'A clean BPE vocabulary. Fewer tokens wasted on “th” + “e”.' },
  { id: 'mixedprec', era: 0, rp: 15, name: 'Mixed-Precision Training',
    fx: { algo: 1.3 },
    desc: 'FP16/BF16 with loss scaling. Same model, far fewer FLOPs wasted.' },
  { id: 'dataclean1', era: 0, rp: 12, name: 'Dedup & Filtering',
    fx: { dataQ: 1.1 },
    desc: 'Remove duplicates and spam from the corpus. Cleaner data, lower loss.' },
  { id: 'kernels', era: 0, rp: 20, name: 'Hand-Tuned CUDA Kernels',
    fx: { mfu: 0.06 },
    desc: 'Fused ops and tiled matmuls. The GPUs finally stop waiting on memory.' },
  { id: 'lora', era: 0, rp: 18, name: 'LoRA Fine-Tuning',
    fx: { gigMult: 2.5 },
    desc: 'Low-rank adapters make custom-model gigs cheap to deliver. 2.5× gig pay.' },
  { id: 'chinchilla', era: 0, rp: 30, name: 'Scaling-Law Study',
    fx: { algo: 1.15 },
    desc: 'Fit your own loss curves. Now you *know* it’s ~20 tokens per parameter.' },

  // ── Era 1: Scale (office) ──────────────────────────────────────
  { id: 'flash', era: 1, rp: 60, deps: ['kernels'], name: 'FlashAttention',
    fx: { mfu: 0.08 },
    desc: 'IO-aware exact attention. Long contexts stop being a memory bandwidth tragedy.' },
  { id: 'zero', era: 1, rp: 80, deps: ['mixedprec'], name: 'ZeRO / FSDP Sharding',
    fx: { memEff: 2 },
    desc: 'Shard optimizer states across the cluster. 2× larger models fit in the same VRAM.' },
  { id: 'pipeline', era: 1, rp: 120, deps: ['zero'], name: '3D Parallelism',
    fx: { mfu: 0.06, algo: 1.1, ppMult: 3 },
    desc: 'Tensor + pipeline + data parallel. One model, every GPU, no idle bubbles.' },
  { id: 'instruct', era: 1, rp: 90, deps: ['lora'], name: 'Instruction Tuning',
    fx: { revMult: 1.5 },
    desc: 'Models that follow instructions are models people pay for.' },
  { id: 'rlhf', era: 1, rp: 150, deps: ['instruct'], name: 'RLHF',
    fx: { revMult: 1.5, demandMult: 1.3 },
    desc: 'Reinforcement learning from human feedback. Suddenly it’s *helpful*.' },
  { id: 'datapipe', era: 1, rp: 70, deps: ['dataclean1'], name: 'Streaming Data Pipeline',
    fx: { dataQ: 1.12 },
    desc: 'Tokenize and shuffle at line rate. No GPU ever starves for data again.' },
  { id: 'checkpoint', era: 1, rp: 50, name: 'Checkpoint & Auto-Resume',
    fx: { mfu: 0.02, outageGuard: true },
    desc: 'Crash at 3am, resume at 3:01am. Outages barely dent your runs.' },
  { id: 'expmgr', era: 1, rp: 100, name: 'Experiment Cluster Manager',
    fx: { maxRuns: 1, rpMult: 1.25 },
    desc: 'A proper scheduler: run two training jobs at once, sweep faster.' },
  { id: 'quant', era: 1, rp: 110, name: 'INT8 Quantization',
    fx: { infEff: 2 },
    desc: 'Serve in 8-bit. Half the serving FLOPs, customers can’t tell.' },

  // ── Era 2: Frontier (colo) ─────────────────────────────────────
  { id: 'moe', era: 2, rp: 1000, deps: ['pipeline'], name: 'Mixture of Experts',
    fx: { algo: 1.8, infEff: 2 },
    desc: 'Route tokens to sparse experts. Frontier quality at a fraction of the FLOPs.' },
  { id: 'muon', era: 2, rp: 2400, name: 'Second-Order Optimizer',
    fx: { algo: 1.35 },
    desc: 'Beyond Adam: curvature-aware updates. Same loss in fewer steps.' },
  { id: 'specdec', era: 2, rp: 1600, deps: ['quant'], name: 'Speculative Decoding',
    fx: { infEff: 1.8 },
    desc: 'A small draft model proposes, the big one verifies. Serving throughput soars.' },
  { id: 'distill', era: 2, rp: 3200, name: 'Frontier Distillation',
    fx: { algo: 1.3, infEff: 1.5 },
    desc: 'Big teachers, small students. Capability gets cheaper to make and serve.' },
  { id: 'synthData', era: 2, rp: 4800, deps: ['distill'], name: 'Synthetic Data Research',
    fx: { algo: 1.15, unlock: 'synthData' },
    desc: 'Model-generated, verifier-filtered data. Unlocks the Synthetic Data Engine.' },
  { id: 'reasoning', era: 2, rp: 6000, deps: ['rlhf'], name: 'RL on Reasoning Traces',
    fx: { algo: 1.6, revMult: 1.3 },
    desc: 'Reward correct chains of thought. The model learns to *think* before answering.' },
  { id: 'agents', era: 2, rp: 4000, deps: ['instruct'], name: 'Agentic Scaffolding',
    fx: { revMult: 1.4, demandMult: 1.4 },
    desc: 'Tools, memory, multi-step plans. The API stops chatting and starts *doing*.' },
  { id: 'powerDeal', era: 2, rp: 2800, money: 10e6, name: 'Direct Power Contracts',
    fx: { powerMult: 0.7 },
    desc: 'PPAs straight from generators. 30% off every kWh, forever.' },
  { id: 'customSilicon', era: 2, rp: 10e3, money: 50e6, deps: ['pipeline'], name: 'Custom Training Silicon',
    fx: { unlock: 'mx1', ppMult: 3 },
    desc: 'Tape out the Mogul MX-1. Your workload, your chip, your margins.' },
  { id: 'autoML', era: 2, rp: 3600, deps: ['expmgr'], name: 'AutoML Pipeline',
    fx: { maxRuns: 1, rpMult: 1.2 },
    desc: 'Automated hyperparameter sweeps run between your launches: +1 training slot, faster research.' },
  { id: 'multimodalR', era: 2, rp: 4400, name: 'Multimodal Pretraining',
    fx: { algo: 1.2, demandMult: 1.5 },
    desc: 'One model: text, vision, audio. Whole new markets open.' },

  // ── Era 3: Superintelligence (hyperscale+) ─────────────────────
  { id: 'worldmodel', era: 3, rp: 40e3, name: 'World-Model Pretraining',
    fx: { algo: 2.0 },
    desc: 'Predict the world, not just the next token. Sample efficiency doubles.' },
  { id: 'selfplay', era: 3, rp: 60e3, deps: ['reasoning'], name: 'Self-Play Curriculum',
    fx: { algo: 2.0 },
    desc: 'Models generate problems just beyond their ability and learn from solving them.' },
  { id: 'aiResearch', era: 3, rp: 100e3, deps: ['agents'], name: 'AI Research Assistants',
    fx: { rpMult: 3, algo: 1.5 },
    desc: 'Your models run the ablations now. Research throughput triples.' },
  { id: 'continual', era: 3, rp: 75e3, name: 'Continual Learning',
    fx: { algo: 1.8 },
    desc: 'No more training from scratch — models keep learning in deployment.' },
  { id: 'waferscale', era: 3, rp: 150e3, money: 500e6, deps: ['customSilicon'], name: 'Wafer-Scale Integration',
    fx: { mfu: 0.08, powerMult: 0.85, ppMult: 10 },
    desc: 'A whole wafer as one chip. Interconnect overhead nearly vanishes.' },
  { id: 'recursion', era: 3, rp: 300e3, reqCap: 80, deps: ['aiResearch', 'selfplay'], name: 'Recursive Self-Improvement',
    fx: { algo: 3.0 },
    desc: 'The model improves the code that trains the model. Handle with care.' },

  // ── Era 4: Beyond Silicon (factory+, post-AGI) ─────────────────
  // Real, plausible future technologies. All reqCap ≥ 100 so the pre-AGI
  // balance is untouched. `real:` is shown to the player as an explainer.
  { id: 'optical', era: 4, rp: 800e3, money: 20e9, reqCap: 100, deps: ['customSilicon'], name: 'Photonic Computing',
    fx: { unlock: 'px1', ppMult: 5, mfu: 0.04 },
    desc: 'Matrix multiplication as light interference. Unlocks the PX-1 Photonic Mesh.',
    real: 'Photonic chips compute matrix multiplications by passing light through meshes of interferometers — the math happens at light speed with almost no resistive heat. As of the mid-2020s, companies like Lightmatter and Lightelligence ship photonic interconnects and accelerator prototypes; co-packaged optics are already replacing copper between AI racks, and full optical matmul engines are the natural next step.' },
  { id: 'analog', era: 4, rp: 1.2e6, reqCap: 100, name: 'Analog In-Memory Computing',
    fx: { mfu: 0.05, powerMult: 0.75 },
    desc: 'Memristor crossbars where physics does the matmul: Ohm\'s law multiplies, Kirchhoff\'s law adds.',
    real: 'In a memristor crossbar, weights are stored as conductances; applying input voltages makes the array compute a matrix-vector product in a single step, in place — no data shuffling between memory and processor. IBM, HP and many labs have demonstrated analog AI inference chips with orders-of-magnitude better energy per operation; precision and drift are the open problems.' },
  { id: 'neuro', era: 4, rp: 1.5e6, reqCap: 100, name: 'Neuromorphic Serving',
    fx: { infEff: 5, powerMult: 0.8 },
    desc: 'Spiking, event-driven inference chips. Brains do this on 20 watts.',
    real: 'Neuromorphic processors like Intel\'s Loihi 2 and IBM\'s NorthPole compute only when "spikes" arrive, instead of clocking every transistor every cycle — the human brain runs general intelligence on ~20 W this way, while a GPU cluster needs megawatts. They already excel at low-power sensing and inference; mapping large language models onto them is active research.' },
  { id: 'cryo', era: 4, rp: 3e6, money: 30e9, reqCap: 105, name: 'Superconducting Logic',
    fx: { ppMult: 4, powerMult: 0.6 },
    desc: 'Josephson junctions switch in picoseconds with zero electrical resistance.',
    real: 'Superconducting single-flux-quantum logic switches in picoseconds and moves signals with zero resistance — potentially 100× the clock at a fraction of the power, which is why it\'s also the cryogenic backbone of quantum computers. The catch: it needs ~4 K cooling, and the cryocooler overhead eats most of the win unless you build very large machines. A natural fit for, say, a dedicated AI megastructure.' },
  { id: 'fusion', era: 4, rp: 4e6, money: 200e9, reqCap: 105, name: 'Fusion Power On-Site',
    fx: { powerMult: 0.25 },
    desc: 'Compact tokamaks behind the substation. Q > 10, fuel from seawater.',
    real: 'Fusion crossed a threshold in December 2022 when the National Ignition Facility got more energy out of a fuel pellet than the laser put in. Private ventures like Commonwealth Fusion Systems are now building compact high-field tokamaks (SPARC) targeting net electricity in the early 2030s — and AI datacenters, with their bottomless demand for firm clean power, are first in line as customers.' },
  { id: 'reversible', era: 4, rp: 5e6, reqCap: 110, deps: ['cryo'], name: 'Reversible Computing',
    fx: { powerMult: 0.4 },
    desc: 'Never erase a bit, never pay the Landauer tax.',
    real: 'Landauer\'s principle (1961, experimentally confirmed in 2012) says erasing one bit must dissipate at least kT·ln2 ≈ 3×10⁻²¹ J of heat — a hard floor for ordinary computing. Reversible logic sidesteps it by never destroying information: every gate can run backwards, so in principle computation can approach zero energy. Today\'s chips run about a thousand times above the Landauer limit, so there is enormous headroom.' },
  { id: 'embodied', era: 4, rp: 2e6, money: 50e9, reqCap: 100, deps: ['multimodalR'], name: 'Embodied AI Fleets',
    fx: { dataQ: 1.08, demandMult: 2 },
    desc: 'A million robots gathering grounded, real-world experience. Unlocks the Embodied Experience Stream.',
    real: 'The web is running out of high-quality text, but the physical world generates unlimited grounded data. Robot foundation models (RT-2, π0, GR00T) already transfer web knowledge into manipulation skills, and "sim-to-real" training does millions of practice years in simulation. Fleets of robots sharing one brain turn every grasp and stumble into training data for all of them at once.' },
  { id: 'quantumAI', era: 4, rp: 8e6, money: 150e9, reqCap: 115, deps: ['cryo'], name: 'Quantum Machine Learning',
    fx: { unlock: 'qc1', algo: 2 },
    desc: 'Hybrid loops: classical chips keep doing the tensor math; error-corrected QPUs (on your superconducting cryo plant) handle the sampling and optimization they can\'t. Unlocks the QC-1 hybrid pod.',
    real: 'In 2024 Google\'s Willow chip demonstrated "below-threshold" quantum error correction — logical qubits that get better as you add more physical ones, the key milestone for scaling. Useful quantum machine learning is still speculative: QPUs won\'t run today\'s transformers, but they could sample probability distributions, optimize, and simulate quantum chemistry in ways classical hardware fundamentally cannot.' },
  { id: 'worldSim', era: 4, rp: 12e6, reqCap: 120, deps: ['embodied', 'worldmodel'], name: 'Full World Simulation',
    fx: { algo: 2.5 },
    desc: 'A faithful physics-and-society simulator. The model rehearses reality before touching it.',
    real: 'World models — neural networks that predict what happens next in an environment — already power video-generation systems and robot planners (Genie, Sora-class models, MuZero\'s learned dynamics). Scaled up, a model that can simulate outcomes can run experiments in imagination: try a million designs, policies or proofs internally and only act on the best one.' },
  { id: 'nanofab', era: 4, rp: 20e6, money: 300e9, reqCap: 130, deps: ['aiResearch'], name: 'Atomically Precise Manufacturing',
    fx: { ppMult: 4, mfu: 0.04 },
    desc: 'Assemblers place atoms like bricks. Compute gets printed, not fabbed.',
    real: 'Feynman\'s "plenty of room at the bottom" (1959) and Drexler\'s molecular assemblers remain the far frontier of manufacturing — but the bottom-up path is real today: DNA origami self-assembles nanostructures, scanning-tunneling microscopes place individual atoms, and 2D materials are grown a single atomic layer at a time. AI-designed proteins (AlphaFold\'s descendants) may be the bootstrap tool that makes molecular machinery practical.' },
  { id: 'omega', era: 4, rp: 50e6, reqCap: 150, deps: ['worldSim', 'quantumAI', 'recursion'], name: 'Ω-Recursion',
    fx: { algo: 4, rpMult: 3 },
    desc: 'The model redesigns its own architecture, end to end. Each generation births the next. The curve goes vertical.',
    real: 'I. J. Good predicted it in 1965: "an ultraintelligent machine could design even better machines; there would then unquestionably be an intelligence explosion." Whether the real curve is a slow takeoff over decades or a fast one over months is one of the most consequential open questions in AI — it depends on exactly the feedback loops this game lets you play with.' },

  // ── The Kardashev climb: stellar, then galactic compute ─────────
  { id: 'vonNeumann', era: 4, rp: 120e6, money: 5e12, reqCap: 180, deps: ['nanofab'], name: 'Self-Replicating Fabricators',
    fx: { unlock: 'dysonNode', ppMult: 2 },
    desc: 'Fabs that build fabs that build fabs. Exponential construction — the only way anything Dyson-scale ever gets built. Unlocks Swarm Collectors.',
    real: 'John von Neumann formalized self-reproducing machines in the 1940s, and every serious Dyson-swarm proposal depends on them: land one seed factory on Mercury, let it double, and ~40 doublings later you have a swarm. Freeman Dyson\'s 1960 Science paper proposed hunting such megastructures by their waste-heat infrared glow — a technosignature SETI surveys still search for today.' },
  { id: 'lloydCore', era: 4, rp: 500e6, money: 100e12, reqCap: 215, deps: ['vonNeumann'], name: 'Lloyd-Limit Cores',
    fx: { unlock: 'omegaCore', algo: 2 },
    desc: 'Computation at the edge of physics: ~5×10⁵⁰ ops per second per kilogram, powered by black-hole spin. Unlocks Omega Cores.',
    real: 'Seth Lloyd ("Ultimate physical limits to computation", Nature 2000) showed a 1 kg "ultimate laptop" could do 5.4×10⁵⁰ operations per second — bounded by energy via the Margolus–Levitin theorem — and later estimated the observable universe has performed ~10¹²⁰ operations since the Big Bang. The Penrose process (1969) can extract up to 29% of a rotating black hole\'s mass-energy: the densest battery physics permits.' },
];

export const ERA_NAMES = ['Foundations', 'Scale', 'Frontier', 'Superintelligence', 'Beyond Silicon'];

export const RESEARCH_BY_ID = Object.fromEntries(RESEARCH.map(r => [r.id, r]));
